### PR TITLE
Updated songs url to new songlist

### PR DESCRIPTION
**Pull request by StelFoog**
Updated the SONGBOOK_DEFAULT_URL link to new songlist repo (https://github.com/insektionen/songlist)

### CODE REVIEW

**Comment by wsv-accidis** [comment]
Because the app is published in Google Play under my name, the content inside is my responsibility, so I'm not willing to point at a repo where I have no control over the contents.

Feel free to either fork this app and publish it in Google Play yourself, or continue contributing to the songs stored in this repo through PRs.

**Comment by StelFoog** [comment]
Very understandable! 👍

**Comment by wsv-accidis** [comment]
@StelFoog Please let me know how you want to proceed. I earn no money from this app and I have no prestige in it. If there is a new and better one that people prefer then I have no problems with that. But it's helpful to know if I should just retire this app or continue looking out for PRs. According to what I've heard, people still prefer the UI of the native Android app to the web app.

**Comment by StelFoog** [comment]
@wsv-accidis Will do! For now the current plan is to have an entirely reworked version of the web app out, which will have an expanded set of features. We have been talking about creating a companion app which mirrors those features for ease of use but for now it's simply an idea and nowhere near production ready.

So for now at least I think there will still be people interested in you maintaining this repo, since, as you stated, people prefer this app's UI over the old web app.

**Comment by wsv-accidis** [comment]
@StelFoog Ok then! I will be happy to continue accepting PRs for any updates to the songs in this app. If the new web app changes things then lmk.

**Pull request closed without merging**
